dependencies :
        - python=3
        - pip:
        - spacy
        - ipykernel
        - scipy
        - numpy
        - scikit
        - learn
        - matplotlib
        - pandas
        - thinc
        - tqdm
        - sklearn
        - Pillow
        - xgboost
        - sympy
        - requests
        - lightgbm
        - catboost
        - torch
